/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import beans.Device;
import beans.Regula;
import java.awt.ItemSelectable;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.util.List;
import javax.swing.JComboBox;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import parsere.ParserFapte;

/**
 *
 * @author Alexis
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private Object[][] vectorObiecte;
    private Object[][] vectorRezultate;
    private List<Device> listDevice;
    private List<Device> listRezultate;
    ParserFapte parserFapte;
    
    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        String caleXml = "C:\\Users\\Alexis\\Documents\\Proiecte personale\\Parser XML Interogari\\tema2.xml";
        
        parserFapte = new ParserFapte();
        
        try {
            listDevice = parserFapte.parsareFapte(caleXml);
//            listDevice.forEach((Device t) -> {
//                System.out.println(t.toString());
//                
//            });
            
            vectorObiecte = new Object[listDevice.size()][10];
            for (int i = 0; i < listDevice.size(); i++) {
                vectorObiecte[i] = parserFapte.getAsVectObj(listDevice.get(i));
            }
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            System.err.println("Nu s-a putut parsa XML-ul pentru fapte! " + ex.getMessage());
        }
        
        initComponents();
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            vectorObiecte,
            new String [] {
                "Nume Device", "Tip device", "Pret", "Magazin", "Placa de baza", "Procesor", "Placa video", "Memorie RAM", "Memorie ROM", "Display"
            }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nume Device", "Tip device", "Pret", "Magazin", "Placa de baza", "Procesor", "Placa video", "Memorie RAM", "Memorie ROM", "Display"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Deviceuri cu ssd si placa video de gaming, care se gaseste la altex", "2. Deviceuri care au mai putin de 1 TB memorie de stocare si au 32gb memorie RAM si sunt vandute de evomag", "3. Deviceuri care au un pret cuprins intre 2000 si 3000 de lei si au un procesor si o placa video performanta", "4. Laptopuri care au display de 15.6\", dar nu au procesor de la firma amd", "5. Deviceuri office (procesor cu indicativ u si placa video multimedia) sub 3000 de lei", "6. Laptopuri cu memorie de acces in timpul rularii aplicatiilor mai mare de 20 GB" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Alegeti regula:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nume Device", "Tip device", "Pret", "Magazin", "Placa de baza", "Procesor", "Placa video", "Memorie RAM", "Memorie ROM", "Display"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            JComboBox cb = (JComboBox)evt.getSource();
            int index = cb.getSelectedIndex();
//            System.out.println(index);

            Regula regula = new Regula();

            switch (index) {
                case 0:
                    listRezultate = regula.regula1(listDevice);
                    break;
                case 1:
                    listRezultate = regula.regula2(listDevice);
                    break;                    
                case 2:
                    listRezultate = regula.regula3(listDevice);
                    break;
                case 3:
                    listRezultate = regula.regula4(listDevice);
                    break;
                case 4:
                    listRezultate = regula.regula5(listDevice);
                    break;                    
                case 5:
                    listRezultate = regula.regula6(listDevice);
                    break;
            }
            
            vectorRezultate = new Object[listRezultate.size()][10];
            for (int i = 0; i < listRezultate.size(); i++) {
                vectorRezultate[i] = parserFapte.getAsVectObj(listRezultate.get(i));
            }
            
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
            vectorRezultate,
            new String [] {
                "Nume Device", "Tip device", "Pret", "Magazin", "Placa de baza", "Procesor", "Placa video", "Memorie RAM", "Memorie ROM", "Display"
            }
        ));
       }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
